### PR TITLE
Progress HUD added

### PR DESCRIPTION
**Pull request by durul**
Progress HUD added

### CODE REVIEW

**Comment by onmyway133** [comment]
@durul Hi, thanks for you PR. I was thinking of `MBProgressHUD` before, or some other `HUD` libraries, but in the end this is not a hard task and I don't want unnecessary dependencies, so I make a custom one `LoadingIndicator`

**Comment by durul** [comment]
Won't you merge ? :)

**Comment by onmyway133** [comment]
@durul Hi, sorry for that, but I don't like unnecessary dependencies, and it's more fun creating our own 😛 . Feel free to close this

**Comment by durul** [comment]
no problem. 😛 😛 😛

**Pull request closed without merging**
